id: omni-clustbench-envmodules
description: "Clustering benchmark on Gagolewski's, true number of clusters plus minus 2."
version: "1.5.0"
benchmarker: "Izaskun Mallona, Daniel Incicau, Ben Carrillo, Mark Robinson"
storage:
  api: S3
  endpoint: http://omnibenchmark.mls.uzh.ch:9000
  bucket_name: clusteringexampleenvmodules
software_backend: envmodules
software_environments:
  clustbench:
    description: "clustbench python"
    envmodule: clustbench
  fcps:
    description: "R deps"
    envmodule: fcps
#metric_collectors:
#  - id: plotting
#    name: "Single-backend metric collector."
#    software_environment: "fcps"
#    repository:
#      url: https://github.com/imallona/clustering_report
#      commit: 040
#    inputs:
#      - metrics.scores
#    outputs:
#      - id: plotting.html
#        path: "{name}/plotting_report.html"
stages:
  ## clustbench data ##########################################################

  - id: data
    modules:
      - id: clustbench
        name: "clustbench datasets, from https://www.sciencedirect.com/science/article/pii/S0020025521010082#t0005 Table1"
        software_environment: "clustbench"
        repository:
          url: https://github.com/imallona/clustbench_data
          commit: fc67ebd
        parameters:  # comments depict the possible cardinalities and the number of curated labelsets
          - dataset_generator: "fcps"
            dataset_name: ["atom", "chainlink", "engytime", "hepta", "lsun", "target", "tetra", "twodiamonds", "wingnut"]
          - dataset_generator: "graves"
            dataset_name: ["dense", "fuzzyx", "line", "parabolic", "ring", "ring_noisy", "ring_outliers", "zigzag", "zigzag_noisy", "zigzag_outliers"] 
          - dataset_generator: "other"
            dataset_name: ["chameleon_t4_8k", "chameleon_t5_8k", "hdbscan", "iris", "iris5", "square"]
          - dataset_generator: "sipu"
            dataset_name: ["aggregation", "compound", "flame", "jain", "pathbased", "r15", "spiral", "unbalance"]
          - dataset_generator: "uci"
            dataset_name: ["ecoli", "ionosphere", "sonar", "statlog", "wdbc", "wine", "yeast"]
          - dataset_generator: "wut"
            dataset_name: ["circles", "cross", "graph", "isolation", "labirynth", "mk1", "mk2", "mk3", "mk4", "olympic", "smile", "stripes", "trajectories", "trapped_lovers", "twosplashes", "windows", "x1", "x2", "x3", "z1", "z2", "z3"]
    outputs:
      - id: data.matrix
        path: "{dataset}.data.gz"
      - id: data.true_labels
        path: "{dataset}.labels0.gz"

  ## clustbench methods (fastcluster) ###################################################################

  - id: clustering
    modules:
      - id: fastcluster
        name: "fastcluster algorithm"
        software_environment: "clustbench"
        repository:
          url: https://github.com/imallona/clustbench_fastcluster
          commit: e644ce5
        parameters:
          - linkage: ["complete", "ward", "average", "weighted", "median", "centroid"]
      - id: sklearn
        name: "sklearn"
        software_environment: "clustbench"
        repository:
          url: https://github.com/imallona/clustbench_sklearn
          commit: dcf35e1
        parameters:
          - method: ["birch", "kmeans", "gm"]
          # "spectral" ## too slow
      - id: agglomerative
        name: "agglomerative"
        software_environment: "clustbench"
        repository:
          url: https://github.com/imallona/clustbench_agglomerative
          commit: 9d086a9
        parameters:
          - linkage: ["average", "complete", "ward"]
      - id: genieclust
        name: "genieclust"
        software_environment: "clustbench"
        repository:
          url: https://github.com/imallona/clustbench_genieclust
          commit: 7d9e799
        parameters:
          - method: "genie"
            gini_threshold: 0.5
          - method: ["gic", "ica"]
      - id: fcps
        name: "fcps"
        software_environment: "fcps"
        repository:
          url: https://github.com/imallona/clustbench_fcps
          commit: e780fed
        parameters:
          - method: ["FCPS_Minimax", "FCPS_MinEnergy", "FCPS_HDBSCAN_2", "FCPS_HDBSCAN_4", "FCPS_HDBSCAN_8", "FCPS_Diana", "FCPS_Fanny", "FCPS_Hardcl", "FCPS_Softcl", "FCPS_Clara", "FCPS_PAM"]
            seed: 2
          # - "FCPS_AdaptiveDensityPeak" # not in Conda
    inputs:
        - data.matrix
        - data.true_labels
    outputs:
      - id: clustering.predicted_ks_range
        path: "{dataset}_ks_range.labels.gz"

  - id: metrics
    modules:
      - id: partition_metrics
        name: "clustbench partition metrics"
        software_environment: "clustbench"
        repository:
          url: https://github.com/imallona/clustbench_metrics
          commit: c4eda85
        parameters:
          - metric: ["normalized_clustering_accuracy", "adjusted_fm_score", "adjusted_rand_score"]
          # - "adjusted_mi_score"
          # - "adjusted_rand_score"
          # - "fm_score"
          # - "mi_score"
          # - "normalized_clustering_accuracy"
          # - "normalized_mi_score"
          # - "normalized_pivoted_accuracy"
          # - "pair_sets_index"
          # - "rand_score"
    inputs:
        - clustering.predicted_ks_range
        - data.true_labels
    outputs:
      - id: metrics.scores
        path: "{dataset}.scores.gz"
