name: Run Benchmark
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    workflow_dispatch:

jobs:
  run-benchmark:
    name: Run Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip packages
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Install omnibenchmark CLI
        run: |
          pip install git+https://github.com/omnibenchmark/omnibenchmark.git@dev

      - name: Load benchmark cache
        id: cache-benchmark
        uses: actions/cache@v3
        with:
          path: out/
          key: benchmark-${{ runner.os }}-${{ hashFiles('Clustering.yaml') }}

      - name: Run benchmark
        run: |
          ob run benchmark -b Clustering.yaml --local --threads 20

  upload-artifact:
    name: Benchmark Artifact
    runs-on: ubuntu-latest
    needs: run-benchmark
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Load cached output
        uses: actions/cache@v3
        with:
          path: out/
          key: benchmark-${{ runner.os }}-${{ hashFiles('Clustering.yaml') }}

      - name: Zip output folder
        run: |
          zip -r benchmark_output.zip out/

      - name: Upload zipped output
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-output-zip
          path: benchmark_output.zip
          retention-days: 7
    
